name: artifacts
on: [push]
jobs:
  example-job:
    name: Save output
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 100 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  example-job1:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        run: |
          chmod -v +x .github/scripts/script.sh 
          ./.github/scripts/script.sh
        shell: bash
