name: Shell commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, world!"
      - name: multiple script
        run: |
          node -v
          npm -v
      - name: python script
        run: |
          import platform
          print(platform.processor())
        shell: python 
  run-on-window:
    runs-on: window:latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Get Location
        run: pwd
        shell: bash
     
